'use client'
import MultiRange from "@/components/multiRange/MultiRange";
import Table from "@/components/table/Table";
import Tooltip from "@/components/tooltip/Tooltip";
import { useMemo, useState } from "react";


const data = [
  {
    key: 1,
    question: `What's your first name? 1`,
    section: 'page1',
    type: 'Subc4',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 2,
    question: `What's your first name? 2`,
    section: 'page1',
    type: 'Subc4',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 3,
    question: `What's your first name? 3`,
    section: 'page1',
    type: 'dddd',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 4,
    question: `What's your first name? 4`,
    section: 'page1',
    type: 'aaaa',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 5,
    question: `What's your first name? 5`,
    section: 'page1',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 6,
    question: `What's your first name? 6`,
    section: 'page2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 7,
    question: `What's your first name? 6`,
    section: 'page2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 8,
    question: `What's your first name? 6`,
    section: 'page2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 9,
    question: `What's your first name? 6`,
    section: 'page2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 10,
    question: `What's your first name? 6`,
    section: 'page2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 11,
    question: `What's your first name? 6`,
    section: 'page3',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 12,
    question: `What's your first name? 6`,
    section: 'page3',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 13,
    question: `What's your first name? 6`,
    section: 'page3',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 14,
    question: `What's your first name? 6`,
    section: 'page3',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 15,
    question: `What's your first name? 6`,
    section: 'page3',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 1,
    question: `What's your first name? 1`,
    section: 'page4',
    type: 'Subc4',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 2,
    question: `What's your first name? 2`,
    section: 'page4',
    type: 'Subc4',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 3,
    question: `What's your first name? 3`,
    section: 'page4',
    type: 'dddd',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 4,
    question: `What's your first name? 4`,
    section: 'page4',
    type: 'aaaa',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 5,
    question: `What's your first name? 5`,
    section: 'page4',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 6,
    question: `What's your first name? 6`,
    section: 'page5',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 7,
    question: `What's your first name? 6`,
    section: 'page5',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 8,
    question: `What's your first name? 6`,
    section: 'page5',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 9,
    question: `What's your first name? 6`,
    section: 'page5',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 10,
    question: `What's your first name? 6`,
    section: 'page5',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 11,
    question: `What's your first name? 6`,
    section: 'page6',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 12,
    question: `What's your first name? 6`,
    section: 'page6',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 13,
    question: `What's your first name? 6`,
    section: 'page6',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 14,
    question: `What's your first name? 6`,
    section: 'page6',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 15,
    question: `What's your first name? 6`,
    section: 'page6',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 15,
    question: `What's your first name? 6`,
    section: 'page7',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 15,
    question: `What's your first name? 6`,
    section: 'page7',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 15,
    question: `What's your first name? 6`,
    section: 'page7',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 1,
    question: `What's your first name? 1`,
    section: 'Section #2',
    type: 'Subc4',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 2,
    question: `What's your first name? 2`,
    section: 'Section #2',
    type: 'Subc4',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 3,
    question: `What's your first name? 3`,
    section: 'page7',
    type: 'dddd',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 4,
    question: `What's your first name? 4`,
    section: 'page7',
    type: 'aaaa',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 5,
    question: `What's your first name? 5`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 6,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 7,
    question: `What's your first name? 6`,
    section: 'page8',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 8,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 9,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 10,
    question: `What's your first name? 6`,
    section: 'page8',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 11,
    question: `What's your first name? 6`,
    section: 'page8',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 12,
    question: `What's your first name? 6`,
    section: 'page8',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 13,
    question: `What's your first name? 6`,
    section: 'page8',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 14,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 15,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 1,
    question: `What's your first name? 1`,
    section: 'Section #2',
    type: 'Subc4',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 2,
    question: `What's your first name? 2`,
    section: 'Section #2',
    type: 'Subc4',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 3,
    question: `What's your first name? 3`,
    section: 'Section #6',
    type: 'dddd',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 4,
    question: `What's your first name? 4`,
    section: 'Section #1',
    type: 'aaaa',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 5,
    question: `What's your first name? 5`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 6,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 7,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 8,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 9,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 10,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 11,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 12,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 13,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 14,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 15,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 15,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 15,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
  {
    key: 15,
    question: `What's your first name? 6`,
    section: 'Section #2',
    type: 'bbbb',
    subType: 'Bio',
    lastUpdated: '4.3.22',
    actions: 'a',
  },
]

const customProps = { id: 'my-table-id' };

export default function QuestionsListPage() {
  const columns = useMemo(
    () => [
      {
        Header: "Question",
        accessor: "question",
      },
      {
        Header: "Section",
        accessor: "section",
      },
      {
        Header: "Type",
        accessor: "type",
      },
      {
        Header: "Sub Type",
        accessor: "subType",
      },
      {
        Header: "Last Updated",
        accessor: "lastUpdated",
      },
      {
        Header: "Actions",
        accessor: "actions",
        disableSortBy: true,
      },
    ],
    []
  );

  const [open, setOpen] = useState(false);
  const handleToggle = () => setOpen((prev) => !prev);

  
  return (
    <div className="text-[#344767]">
      
      {/* <Tooltip text={'checking'} direction="right" color="primary">
        <div>Questions</div>
      </Tooltip>

      <br />
      <MultiRange min={0} max={1000} step={10} /> */}

      {/* <Table columns={columns} data={data} /> */}
      
    </div>
  )
}
